## softmax function
## 여러개의 클래스가 있을 때 예측할 때

In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [18]:
x_data = [[1, 2, 1, 1], [2, 1, 3, 2], [3, 1, 3, 4], [4, 1, 5, 5], 
          [1, 7, 5, 5], [1, 2, 5, 6], [1, 6, 6, 6], [1, 7, 7, 7]]
### one_hot_encoding
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

In [19]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

### Shape 주의

In [20]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name = "Weight")
b = tf.Variable(tf.random_normal([nb_classes]), name = "bias")

In [21]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [22]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [34]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict = {X: x_data, Y: y_data}))
    
    # arg_max는 최강자를 찾는거 인덱스를 반환
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.arg_max(a, 1)))
    
    print('--------------')
    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 5.061822
200 0.5422079
400 0.43657726
600 0.358789
800 0.28396827
1000 0.23819396
1200 0.2155962
1400 0.19681588
1600 0.18095063
1800 0.16737339
2000 0.15562806
[[5.6210170e-03 9.9437237e-01 6.6266989e-06]] [1]
--------------
[[5.6210170e-03 9.9437237e-01 6.6266989e-06]
 [8.5660452e-01 1.3603856e-01 7.3569715e-03]
 [1.0247996e-08 3.0573024e-04 9.9969423e-01]] [1 0 2]
