In [1]:
import tensorflow as tf

## hypothesis using matrix

In [6]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

#placeholder
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = "weight1")
w2 = tf.Variable(tf.random_normal([1]), name = "weight2")
w3 = tf.Variable(tf.random_normal([1]), name = "weight3")
b = tf.Variable(tf.random_normal([1]), name = "bias")

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [9]:
#원시적인 방법
cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, y: y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nprediction:\n", hy_val)

0 cost :  22785.758 
prediction:
 [14.478317 25.986668 21.588474 21.100605 23.478569]
10 cost :  8.10586 
prediction:
 [147.99759 186.44777 179.70346 193.28313 145.86583]
20 cost :  7.8595414 
prediction:
 [148.41158 186.92638 180.18488 193.80667 146.22672]
30 cost :  7.821852 
prediction:
 [148.42285 186.92093 180.18935 193.81087 146.21843]
40 cost :  7.7844377 
prediction:
 [148.43285 186.91403 180.19235 193.81345 146.20905]
50 cost :  7.747205 
prediction:
 [148.44281 186.90717 180.19537 193.81601 146.19966]
60 cost :  7.7101746 
prediction:
 [148.45274 186.90028 180.19833 193.81857 146.19032]
70 cost :  7.6733093 
prediction:
 [148.46268 186.89345 180.20135 193.82117 146.18102]
80 cost :  7.6366806 
prediction:
 [148.47258 186.88666 180.20433 193.82372 146.17172]
90 cost :  7.6002426 
prediction:
 [148.48244 186.87982 180.20728 193.82625 146.16246]
100 cost :  7.5639696 
prediction:
 [148.49228 186.87306 180.21025 193.82883 146.15321]
110 cost :  7.5279527 
prediction:
 [148.50209 

960 cost :  5.073572 
prediction:
 [149.24426 186.35408 180.43619 194.02663 145.44322]
970 cost :  5.0508113 
prediction:
 [149.252   186.34872 180.4385  194.0287  145.43587]
980 cost :  5.028179 
prediction:
 [149.2597  186.3434  180.44081 194.03078 145.42853]
990 cost :  5.005684 
prediction:
 [149.26741 186.33809 180.44315 194.03285 145.42123]
1000 cost :  4.9832945 
prediction:
 [149.27509 186.3328  180.44543 194.03491 145.41394]
1010 cost :  4.9610744 
prediction:
 [149.28273 186.3275  180.44774 194.03696 145.4067 ]
1020 cost :  4.938933 
prediction:
 [149.29036 186.32224 180.45001 194.03899 145.39943]
1030 cost :  4.9169044 
prediction:
 [149.29797 186.31697 180.45229 194.04105 145.39221]
1040 cost :  4.8949914 
prediction:
 [149.30556 186.31172 180.45457 194.04309 145.385  ]
1050 cost :  4.8732023 
prediction:
 [149.31311 186.3065  180.45685 194.04514 145.37779]
1060 cost :  4.8515606 
prediction:
 [149.32066 186.3013  180.45909 194.04715 145.37064]
1070 cost :  4.8299856 
predi

1960 cost :  3.3068137 
prediction:
 [149.92079 185.88635 180.63843 194.21198 144.79655]
1970 cost :  3.293489 
prediction:
 [149.92664 185.8823  180.64015 194.21361 144.79091]
1980 cost :  3.2801852 
prediction:
 [149.9325  185.87825 180.64189 194.21526 144.78526]
1990 cost :  3.2669826 
prediction:
 [149.93831 185.8742  180.64363 194.21689 144.77963]
2000 cost :  3.2538323 
prediction:
 [149.94412 185.87018 180.64537 194.21855 144.77403]


## matrix 사용

In [ ]:
x_data = [[73., 80., 75.], [93, 88, 93],
          [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

#none은 n개 3개의 variable
x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = "weight")
b = tf.Variable(tf.random_normal([1]), name = "bias")

hypothesis = tf.matmul(x, w) + b

cost = tf.reduce_mean(tf.square(hypothesis - y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate= 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={x: x_data, y: y_data})
    if step % 10 == 0:
        print(step, "cost : ", cost_val, "\nprediction:\n", hy_val)

0 cost :  114965.7 
prediction:
 [[-144.48595]
 [-180.20619]
 [-174.00824]
 [-191.39326]
 [-137.5597 ]]
10 cost :  11.33479 
prediction:
 [[155.43147]
 [180.29553]
 [181.18811]
 [195.40819]
 [137.41687]]
20 cost :  10.228209 
prediction:
 [[156.32658]
 [181.39474]
 [182.25902]
 [196.57591]
 [138.25981]]
30 cost :  10.174333 
prediction:
 [[156.317  ]
 [181.40648]
 [182.25845]
 [196.57684]
 [138.27328]]
40 cost :  10.120724 
prediction:
 [[156.3047 ]
 [181.41492]
 [182.2547 ]
 [196.57428]
 [138.28424]]
50 cost :  10.067432 
prediction:
 [[156.29243]
 [181.42331]
 [182.25092]
 [196.57167]
 [138.29514]]
60 cost :  10.014427 
prediction:
 [[156.2802 ]
 [181.43169]
 [182.24715]
 [196.5691 ]
 [138.306  ]]
70 cost :  9.961701 
prediction:
 [[156.26799]
 [181.44003]
 [182.24338]
 [196.56651]
 [138.31683]]
80 cost :  9.909292 
prediction:
 [[156.25583]
 [181.44836]
 [182.23965]
 [196.56398]
 [138.32765]]
90 cost :  9.857103 
prediction:
 [[156.24368]
 [181.45668]
 [182.2359 ]
 [196.5614 ]
 [138

840 cost :  6.6511564 
prediction:
 [[155.42056]
 [182.01987]
 [181.98228]
 [196.3887 ]
 [139.06848]]
850 cost :  6.616674 
prediction:
 [[155.41069]
 [182.02661]
 [181.97925]
 [196.38663]
 [139.07722]]
860 cost :  6.5822396 
prediction:
 [[155.40082]
 [182.03339]
 [181.9762 ]
 [196.38458]
 [139.08597]]
870 cost :  6.548079 
prediction:
 [[155.39099]
 [182.0401 ]
 [181.97316]
 [196.38252]
 [139.09468]]
880 cost :  6.5140595 
prediction:
 [[155.38116]
 [182.04681]
 [181.97014]
 [196.38048]
 [139.10336]]
890 cost :  6.4802446 
prediction:
 [[155.3714 ]
 [182.05353]
 [181.96713]
 [196.37843]
 [139.11203]]
900 cost :  6.446583 
prediction:
 [[155.36163]
 [182.0602 ]
 [181.96411]
 [196.3764 ]
 [139.12068]]
910 cost :  6.413142 
prediction:
 [[155.35188]
 [182.06683]
 [181.96112]
 [196.37436]
 [139.12929]]
920 cost :  6.379903 
prediction:
 [[155.3422 ]
 [182.07346]
 [181.95811]
 [196.37234]
 [139.13788]]
930 cost :  6.346774 
prediction:
 [[155.33252]
 [182.08011]
 [181.95515]
 [196.37035]
